# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\j35\git\mcp_efficiency_correction\ui_template\configuration.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 318)
        Dialog.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.output_button_folder = QtWidgets.QPushButton(Dialog)
        self.output_button_folder.setObjectName("output_button_folder")
        self.gridLayout.addWidget(self.output_button_folder, 1, 2, 1, 1)
        self.output_folder_label = QtWidgets.QLabel(Dialog)
        self.output_folder_label.setObjectName("output_folder_label")
        self.gridLayout.addWidget(self.output_folder_label, 1, 1, 1, 1)
        self.input_folder_label = QtWidgets.QLabel(Dialog)
        self.input_folder_label.setObjectName("input_folder_label")
        self.gridLayout.addWidget(self.input_folder_label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.input_folder_button = QtWidgets.QPushButton(Dialog)
        self.input_folder_button.setObjectName("input_folder_button")
        self.gridLayout.addWidget(self.input_folder_button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(160, 0))
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.time_out_slider = QtWidgets.QSlider(Dialog)
        self.time_out_slider.setToolTip("")
        self.time_out_slider.setMinimum(20)
        self.time_out_slider.setMaximum(120)
        self.time_out_slider.setProperty("value", 35)
        self.time_out_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_out_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.time_out_slider.setTickInterval(10)
        self.time_out_slider.setObjectName("time_out_slider")
        self.horizontalLayout_2.addWidget(self.time_out_slider)
        self.time_out_label = QtWidgets.QLabel(Dialog)
        self.time_out_label.setMinimumSize(QtCore.QSize(30, 0))
        self.time_out_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.time_out_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_out_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_out_label.setObjectName("time_out_label")
        self.horizontalLayout_2.addWidget(self.time_out_label)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(15, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.input_folder_button.clicked.connect(Dialog.select_default_input_folder)
        self.output_button_folder.clicked.connect(Dialog.select_default_output_folder)
        self.cancel_button.clicked.connect(Dialog.cancel_clicked)
        self.save_button.clicked.connect(Dialog.save_clicked)
        self.time_out_slider.sliderMoved['int'].connect(Dialog.time_out_slider_moved)
        self.time_out_slider.sliderPressed.connect(Dialog.time_out_slider_clicked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.output_button_folder.setText(_translate("Dialog", "Select ..."))
        self.output_folder_label.setText(_translate("Dialog", "N/A"))
        self.input_folder_label.setText(_translate("Dialog", "N/A"))
        self.label_3.setText(_translate("Dialog", "Defaut Input Folder:"))
        self.label_5.setText(_translate("Dialog", "Default Output Folder:"))
        self.input_folder_button.setText(_translate("Dialog", "Select ..."))
        self.label.setText(_translate("Dialog", "Run Correction Time Out"))
        self.time_out_label.setText(_translate("Dialog", "35"))
        self.label_4.setText(_translate("Dialog", "s"))
        self.label_2.setText(_translate("Dialog", "(If after running the  correction you realize that the process did not complete, increase the time out)."))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.save_button.setText(_translate("Dialog", "Save"))

