# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\j35\git\mcp_efficiency_correction\ui_template\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_parent_folder = QtWidgets.QPushButton(self.groupBox_2)
        self.select_parent_folder.setObjectName("select_parent_folder")
        self.horizontalLayout_2.addWidget(self.select_parent_folder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_output_folder_button = QtWidgets.QPushButton(self.groupBox)
        self.select_output_folder_button.setMinimumSize(QtCore.QSize(100, 0))
        self.select_output_folder_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.select_output_folder_button.setObjectName("select_output_folder_button")
        self.horizontalLayout.addWidget(self.select_output_folder_button)
        self.output_folder_label = QtWidgets.QLabel(self.groupBox)
        self.output_folder_label.setObjectName("output_folder_label")
        self.horizontalLayout.addWidget(self.output_folder_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.help_button = QtWidgets.QPushButton(self.tab)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_3.addWidget(self.help_button)
        self.configuration_button = QtWidgets.QPushButton(self.tab)
        self.configuration_button.setObjectName("configuration_button")
        self.horizontalLayout_3.addWidget(self.configuration_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.run_correction_button = QtWidgets.QPushButton(self.tab)
        self.run_correction_button.setEnabled(False)
        self.run_correction_button.setMinimumSize(QtCore.QSize(300, 0))
        self.run_correction_button.setObjectName("run_correction_button")
        self.horizontalLayout_3.addWidget(self.run_correction_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logbook = QtWidgets.QTextEdit(self.tab_2)
        self.logbook.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.logbook.setObjectName("logbook")
        self.verticalLayout_4.addWidget(self.logbook)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.select_parent_folder.clicked.connect(MainWindow.select_parent_folder_clicked)
        self.select_output_folder_button.clicked.connect(MainWindow.select_output_folder_clicked)
        self.run_correction_button.clicked.connect(MainWindow.run_correction_clicked)
        self.actionEdit.triggered.connect(MainWindow.edit_config_clicked)
        self.help_button.clicked.connect(MainWindow.help_clicked)
        self.configuration_button.clicked.connect(MainWindow.edit_config_clicked)
        self.tableWidget.itemSelectionChanged.connect(MainWindow.row_selected)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parent Folder"))
        self.select_parent_folder.setText(_translate("MainWindow", "Select Parent Folder ..."))
        self.label.setText(_translate("MainWindow", "Then Select Folder(s) of Images to Correct"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.groupBox.setTitle(_translate("MainWindow", "Output Folder"))
        self.select_output_folder_button.setText(_translate("MainWindow", "Select ..."))
        self.output_folder_label.setText(_translate("MainWindow", "N/A"))
        self.help_button.setText(_translate("MainWindow", "Help"))
        self.configuration_button.setText(_translate("MainWindow", "Configuration ..."))
        self.run_correction_button.setText(_translate("MainWindow", "Run Correction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Input"))
        self.logbook.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Logbook"))
        self.actionEdit.setText(_translate("MainWindow", "Edit ..."))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))

